"""id uzytkownika dla powiadomień

Revision ID: 47955a19d2f4
Revises: 
Create Date: 2024-07-02 14:24:06.633443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47955a19d2f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
